// This is an autogenerated file from genkit, please do not modify it manually.
'use server';

/**
 * @fileOverview An AI agent for categorizing reports based on description and image.
 *
 * - categorizeReport - A function that handles the report categorization process.
 * - CategorizeReportInput - The input type for the categorizeReport function.
 * - CategorizeReportOutput - The return type for the categorizeReport function.
 */

import {ai} from '@/ai/genkit';
import {z} from 'genkit';

const CATEGORIES = ['chair', 'fan', 'window', 'light', 'sanitation', 'other'] as const;

const CategorizeReportInputSchema = z.object({
  description: z.string().describe('The description of the report.'),
  photoDataUri: z
    .string()
    .optional()
    .describe(
      "A photo related to the report, as a data URI that must include a MIME type and use Base64 encoding. Expected format: 'data:<mimetype>;base64,<encoded_data>'."
    ),
});
export type CategorizeReportInput = z.infer<typeof CategorizeReportInputSchema>;

const CategorizeReportOutputSchema = z.object({
  suggestedCategory: z.enum(CATEGORIES).describe('The suggested category for the report.'),
});
export type CategorizeReportOutput = z.infer<typeof CategorizeReportOutputSchema>;

export async function categorizeReport(input: CategorizeReportInput): Promise<CategorizeReportOutput> {
  return categorizeReportFlow(input);
}

const prompt = ai.definePrompt({
  name: 'categorizeReportPrompt',
  input: {schema: CategorizeReportInputSchema},
  output: {schema: CategorizeReportOutputSchema},
  prompt: `You are an AI assistant helping to categorize reports based on their description and attached photo, if available. Choose one category from the available options. Output ONLY the name of the category. Available categories: chair, fan, window, light, sanitation, other.

Description: {{{description}}}
{{#if photoDataUri}}
Photo: {{media url=photoDataUri}}
{{/if}}`,
});

const categorizeReportFlow = ai.defineFlow(
  {
    name: 'categorizeReportFlow',
    inputSchema: CategorizeReportInputSchema,
    outputSchema: CategorizeReportOutputSchema,
  },
  async input => {
    const {output} = await prompt(input);
    return output!;
  }
);
